remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Open Data Hub]
description: [This is a playground to create some insights with the use of open data.]
show_downloads: [true]
google_analytics: [G-55N5ST9LF9]